name: Automated-test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install sqlalchemy pandas numpy

    - name: Run pipline.py
      run: python3 project/pipeline.py
        
    - name: Run test.py
      run: python3 project/test.py